// ============================================================
// milliseconds.dev — .NET vs Python performance benchmarks
// Project : 09 — Date string parsing
// Author  : Mo Mand  |  https://milliseconds.dev
//
// Explicit-format date parser — replaces:
//   Python: dateutil.parser.parse(text)
//
// Key differences from the Python version:
//   - Explicit format list instead of dateutil's heuristic auto-detection
//   - DateTimeOffset (not DateTime) preserves RFC 2822 timezone offsets,
//     matching dateutil's behaviour of keeping the date in the string's zone
//   - No heap allocation per parse; no Python object boxing
//   - Formats cover all 8 patterns generated by python/build_dates.py
// ============================================================

using System.Globalization;

class DateParser
{
    // Covers every pattern produced by python/build_dates.py.
    // Python equivalent: dateutil infers these automatically.
    private static readonly string[] Formats =
    [
        "yyyy-MM-ddTHH:mm:ss",       // ISO 8601 full
        "yyyy-MM-dd",                // ISO 8601 date only
        "ddd, dd MMM yyyy HH:mm:ss zzz",  // RFC 2822
        "MMMM d, yyyy",              // long US  (e.g. "May 27, 2026")
        "M/d/yyyy",                  // short US (e.g. "5/27/2026")
        "dd MMM yyyy",               // day-month (e.g. "27 May 2026")
        "yyyy/MM/dd HH:mm:ss",       // slash with time
        "MM-dd-yyyy HH:mm",          // US with time
    ];

    private static readonly CultureInfo Culture = CultureInfo.InvariantCulture;
    private const DateTimeStyles Styles = DateTimeStyles.AllowWhiteSpaces;

    // Try to parse a date string using the explicit format list.
    // Python equivalent: dateutil.parser.parse(text)
    public bool TryParse(string text, out DateTimeOffset result) =>
        DateTimeOffset.TryParseExact(text, Formats, Culture, Styles, out result);
}
